<a href="https://colab.research.google.com/github/Pragadishwaran074/Python-Programming-for-Machine-Learning/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([[10,20,30],[50,80,70]])
print(a)
print("Array created :",a)

[[10 20 30]
 [50 80 70]]
Array created : [[10 20 30]
 [50 80 70]]


In [2]:
c=np.zeros((3,5))
print("\nArray with all zeros:\n",c)


Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
d=np.random.random((4,4))
print("\nRandom value:",d)


Random value: [[0.24632692 0.53487637 0.90220756 0.05941504]
 [0.45856927 0.48365384 0.39015586 0.03761228]
 [0.84740872 0.39270892 0.53303363 0.42738648]
 [0.63389083 0.71882522 0.70351477 0.34445987]]


In [4]:
e=np.arange(0,20,2)
print("Array:\n",e)

Array:
 [ 0  2  4  6  8 10 12 14 16 18]


In [5]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [6]:
f=(np.full((3,4),(7)))
print(f)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [8]:
import numpy as np
flat=arr.flatten()
print("Original array:\n",arr)
print("Flattened array:\n",flat)

Original array:
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
Flattened array:
 [1 2 3 4 5 6 7 8 1 2 0 1]


In [9]:
print("\n No. of dimensions:",arr.ndim)


 No. of dimensions: 2


In [10]:
print("Arrat shape:",arr.shape)

Arrat shape: (3, 4)


In [11]:
print("Array type:",arr.dtype)

Array type: int64


In [12]:
newtype=arr.astype('f')
print("\n convert array:\n",newtype)
print("\n convert array type:\n",newtype.dtype)


 convert array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

 convert array type:
 float32


In [13]:
size=len(arr)
print("\n size of array:\n",size)


 size of array:
 3
